### ISSUE TITLE
BungeeCord: protocol error: Failed to auth with server

### ISSUE THREAD

**Issue by chaserhkj** [iceiix/stevenarella#125]
Crashes on connecting to server:

```
thread 'main' panicked at 'Err: IOError(Custom { kind: UnexpectedEof, error: StringError("failed to fill whole buffer") })', src/server/mod.rs:441:33
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: std::panicking::begin_panic_fmt
   7: stevenarella::server::Server::entity_tick
   8: stevenarella::server::Server::tick
   9: stevenarella::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
  12: __rust_maybe_catch_panic
  13: std::rt::lang_start_internal
  14: main
  15: __libc_start_main
  16: _start

```

I'm not sure if this is a network issue, since I'm trying to connect to a server across the Pacific ocean, but the handshake went through well and I could connect to the server using the official Java client. The server side seems to be using BungeeCord to balance the load on a set of servers.

**Comment by iceiix** [comment]
@chaserhkj This error can occur if there is a problem parsing the protocol packets. Have not yet tested with BungeeCord, could be an incompatibility there, I'll have to test. Can you share the server version?

**Comment by chaserhkj** [comment]
I don't know specifically about the versions, I'm contacting the server management teams for for info, stay tuned.

**Comment by chaserhkj** [comment]
I could confirm that on that server the BungeeCord version is `git:BungeeCord-Bootstrap:1.14-SNAPSHOT:7d68335:1410 by md_5` and the backend server is running PaperMC with version `1.13.2 build 624`

There are some updates to this issue as well. Using the latest version of stevenarella I won't get the crash anymore but with a error message of `failed to fill whole buffer`, is this a network issue?

I tried reconnecting and sometimes I could get pass that error message but with the server side dropping the connection stating that I'm using a 1.14 client which is too new. It seems that stevenarella could not properly choose the right protocol version under these setup.

**Comment by iceiix** [comment]
Thanks for the versions, I haven't tested with either BungeeCord or PaperMC, I may need to implement BungeeCord support.

"failed to fill whole buffer" occurs when there is a network protocol parsing error, something might be wrong with the packet definitions. It could only occur intermittently if only a specific packet is incorrectly defined.

As of build 1.0.657 (after https://github.com/iceiix/stevenarella/commit/6322cf8b214a093457a67dcfc8cc6b6e977d1f11), the protocol version is now detected by pinging the server right before connecting (instead of from the server list). This should have fixed protocol versioning race conditions, but there could be confusion detecting the version with 1.14 BungeeCord vs 1.13.2 PaperMC, not sure.

Just added in build 1.0.678 with https://github.com/iceiix/stevenarella/commit/4520f6bdae45404b27b285c5b616227db4557d14 an option to log network packets. Could you re-run with --network-debug and attach the full output? I'll also try to setup a test environment on my end.

**Comment by iceiix** [comment]
https://ci.md-5.net/job/BungeeCord/ using build 1411, running `java -jar BungeeCord.jar` with all defaults, connecting with `target/release/stevenarella -n -s localhost:25577`, I can reproduce the outdated server kick:

about to parse id=18, dir=Clientbound state=Play
packet = Some(PluginMessageClientbound(PluginMessageClientbound { channel: "minecraft:register", data: [98, 117, 110, 103, 101, 101, 99, 111, 114, 100, 58, 109, 97, 105, 110] }))
Received plugin message: channel=minecraft:register, data=[98, 117, 110, 103, 101, 101, 99, 111, 114, 100, 58, 109, 97, 105, 110]
about to parse id=1a, dir=Clientbound state=Play
packet = Some(Disconnect(Disconnect { reason: Text(TextComponent { text: "", modifier: Modifier { extra: Some([Text(TextComponent { text: "Kicked whilst connecting to lobby: ", modifier: Modifier { extra: None, bold: None, italic: None, underlined: None, strikethrough: None, obfuscated: None, color: Some(Red) } }), Text(TextComponent { text: "Outdated server! Im still on {}", modifier: Modifier { extra: None, bold: None, italic: None, underlined: None, strikethrough: None, obfuscated: None, color: Some(White) } })]), bold: None, italic: None, underlined: None, strikethrough: None, obfuscated: None, color: None } }) }))

The channel it is trying to register is "bungeecord:main" (which Stevenarella doesn't do anything with yet, maybe it should; adding another plugin channel to support in #134). How about the version detection?

packet = Some(StatusResponse(StatusResponse { status: "{\"version\":{\"name\":\"BungeeCord 1.8.x-1.14.x\",\"protocol\":477},\"players\":{\"max\":1,\"online\":0},\"description\":{\"extra\":[{\"color\":\"dark_blue\",\"text\":\"Another Bungee server\"}],\"text\":\"\"},\"modinfo\":{\"type\":\"FML\",\"modList\":[]}}" }))
about to parse id=1, dir=Clientbound state=Status
packet = Some(StatusPong(StatusPong { ping: 42 }))
[main.rs:94][INFO] Detected server protocol version 477

The server is saying it supports 477 (1.14), so that's what the client tries to use. Hmm...

If I use vanilla 1.14 connecting to BungeeCord 1411, it is kicked with the same error:

<img width="783" alt="Screen Shot 2019-05-05 at 3 06 28 PM" src="https://user-images.githubusercontent.com/43691553/57200992-75ba1000-6f47-11e9-8b12-759cb4420956.png">

So why is BungeeCord advertising itself as supporting this protocol when it doesn't?

**Comment by chaserhkj** [comment]
With the latest version I wasn't able to reproduce the "failed to fill whole buffer" error anymore. It rather consistently showing the version-not-matched error message.

The error logs of the original server is attached [here](https://0bin.net/paste/sgeh-xsTwCJFhUyl#bXPP6+QCU765Qp9o5ShmqyVKgttM07zFskLJ+ZTHozp)

Note that this server belongs to a Chinese community so the server error messages are customized to be in Chinese, the text message of the error which reads "客户端太新了啦！咱还在 1.13.2" means "Client version is too new! I'm still on 1.13.2"

On your local test, I think that error might come from the fact that you might have not supplied a backend server for BungeeCord. I tried to do a local test environment myself as well and here's what I've done:

1. Setting up BungeeCord build 1411, running `java -jar BungeeCord.jar` ([here](https://ci.md-5.net/job/BungeeCord/))
2. Bootstrap PaperMC build 624 on the same box in the different folder, running `java -jar paper-624.jar` ([here](https://papermc.io/downloads))
3. Modifying eula.txt in paperMC folder for it to run, while also set it to offline mode (mentioned [here](https://github.com/SpigotMC/BungeeCord/issues/1737#issuecomment-181139430), as BungeeCord is doing the auth at frontend, backends need to run in offline)

Under this setup I could connect to the server using an official client.

Running `target/release/stevenarella -n -s 127.0.0.1:25577` gives `protocol error: Failed to auth with server` in GUI, which looks different, the whole log is attached [here](https://0bin.net/paste/GXZWgpYbgPCwh+-+#2CfNZMrUp9KDWEwo69ffPq0nO+1b4DW0PgKof9AUQ9O)

**Comment by chaserhkj** [comment]
Also when I was trying to connect to some other servers I constantly got an error message of `Connection throttled! Please wait before reconnecting`, is this a network issue then?

**Comment by iceiix** [comment]
I can repro the "protocol error: Failed to auth with server" error, BungeeCord 1411 with vanilla 1.14. Getting an error from the Mojang session server for some reason:

res = Response { url: "https://sessionserver.mojang.com/session/minecraft/join", status: 403, headers: {"content-type": "application/json", "content-length": "70", "connection": "keep-alive", "accept-ranges": "bytes", "date": "Mon, 06 May 2019 02:04:23 GMT", "server": "Restlet-Framework/2.3.12", "x-cache": "Error from cloudfront", "via": "1.1 (CloudFront)", "x-amz-cf-id": "=="} }

may be an error in how I'm authenticating. Had to rewrite the auth code to remove OpenSSL in https://github.com/iceiix/stevenarella/issues/12 https://github.com/iceiix/stevenarella/issues/2 it could have bugs, needs more investigation..

---

> Under this setup I could connect to the server 127.0.0.1:25577 using an official client.

Using the official 1.14 or 1.13.2 client? Looks like paper-624.jar is 1.13.2. BungeeCord accepting a range of protocols presents a problem for multi-protocol clients, how to choose the version? Right now it defaults to the latest (1.14/477) in the server ping, but maybe we'll need a command-line option or setting to override the default client version.

---

> Connection throttled! Please wait before reconnecting, is this a network issue then?

This may be related to this note on https://www.spigotmc.org/threads/1-8-1-13-bungeecord.392/:

> BungeeCord on different machine to some servers First you need to set connection-throttle to -1 in bukkit.yml.

**Comment by iceiix** [comment]
https://wiki.vg/Protocol_Encryption

Using https://github.com/iceiix/rsa_public_encrypt_pkcs1/ for encrypting to the server's public key. Performs a minimal ASN.1 decoding (using simple_asn1) and PKCS#1 padding. Maybe BungeeCord's public key structure is different in such a way it couldn't be parsed by this naive implementation (wanted to switch to a more well-supported decryption crate anyway, RustCrypto? Ring?)

**Comment by chaserhkj** [comment]
> Using the official 1.14 or 1.13.2 client? 

I was using official 1.13.2 client for that test.

> how to choose the version? Right now it defaults to the latest (1.14/477) in the server ping, but maybe we'll need a command-line option or setting to override the default client version.

Yeah I think providing an override would be a good idea, but also we may run some sniffs to look at how the official client handshakes with such server systems to get a little hint.

> This may be related to this note on https://www.spigotmc.org/threads/1-8-1-13-bungeecord.392/:

I'm pretty sure this problem has nothing to do with BugeeCord, I was trying to connect to a remote plain PaperMC server when encountered this message, since connecting to PaperMC on localhost works just fine and the remote server I was connecting actually has a ping around 100-120ms that might be a network issue. This probably should be on a different issue since it's not related to BugeeCord anymore. I would try to gather some log for this and post it in a different issue.

**Comment by iceiix** [comment]
> I was using official 1.13.2 client for that test.

Aha, that explains it:

> Yeah I think providing an override would be a good idea, but also we may run some sniffs to look at how the official client handshakes with such server systems to get a little hint.

Stevenarella was acting as if it was 1.14, but falls back to the version the server says it supports. BungeeCord supports 1.14-1.8 but the backend servers might not necessarily. I see the same behavior when connecting with the official 1.14 client.

In build 687 https://github.com/iceiix/stevenarella/commit/938905068bcd99d4c26da388edf031c9a9bb97c8 I added a -p or --default-protocol-version command-line flag to change the version the client first advertises to the server. By default it will be the latest (477 = 1.14 at this time), but you can pass -p 404 to emulate 1.13.2 (full list of protocol version numbers at https://github.com/iceiix/stevenarella/blob/master/src/protocol/versions.rs). 

However, it still fails with the protocol error: "Failed to auth with server". I'll use this issue to track that problem, and look forward for your other issues (appreciate helping test, don't think I'd find these bugs on my own). Still tracking this one down, I thought it could be due to the BungeeCord server's public key format, but there's nothing unusual about it... but I might be going in the right direction (rsa_public_encrypt_pkcs1)...

**Comment by iceiix** [comment]
@chaserhkj Are you still able to reproduce this issue? I am retesting now, was going to dig deeper to double-check my protocol encryption math, but I now no longer see "protocol error: Failed to auth with server" when connecting to a BungeeCord build 1411 server to a 1.14 vanilla server or 1.13.2 paper-624 server. It just works. Maybe was an intermittent failure on the session server side?

**Comment by iceiix** [comment]
chaser I think what happened in my testing where I was hitting "protocol error: Failed to auth with server" is #164, no longer seeing any issues here at least in my testing, let me know if you still are...
