### ISSUE TITLE
Matrix-irc bridge doesn't work

### ISSUE THREAD

**Issue by Kezii** [iceiix/stevenarella#336]
The bridge between matrix and irc doesn't seem to be working, messages in irc are not displayed in the matrix chat

The matrix chat has some users but there's a lot of confusion in it

**Comment by iceiix** [comment]
Haven't visited either chatrooms lately, unsure of their status. Matrix was added in #109, on @PureTryOut's request - any idea what may have broken it? Maybe should remove it to avoid confusion if it isn't properly linked to IRC...

But IRC has other problems: even with a bouncer, if I'm offline for a while and log back on, I can see others questions, but not respond (where they would see them) if they have left but log back in. Some kind of semi-asynchronous chat service would be ideal, at least that preserves history so new users can scroll back through the existing messages. Also, the IRC BNC service I was using went out of business. Open to suggestions...

**Comment by PureTryOut** [comment]
Yeah I found out it was broken quite a while ago and asked the Matrix devs what was happening. I don't believe I got a clear answer, but it seems to be something with specific rooms. It has basically never worked properly, in the beginning I just thought no one was talking.

Preferably the bridge just gets fixed, but according to [this page](https://github.com/matrix-org/matrix-appservice-irc/wiki/Bridged-IRC-networks) the bridge has shut down due to a server breach last year. It might be worth considering moving to a different network like Freenode, as the bridge works fine there.

**Comment by iceiix** [comment]
Unfortunate about the Matrix breach, I'll remove the reference to the IRC bridge for now. 

(Will have to think more changing IRC networks. Freenode does seem like a good fit due to focus on open source software, on the other hand EsperNet is popular with Minecraft-related projects. Steven's original developer was on SpigotIRC, a new network for SpigotMC, but then there is: https://www.spigotmc.org/threads/official-spigotmc-discord-server-—-join-now.426794/)

**Comment by PureTryOut** [comment]
Ha, anything but moving to a proprietary and walled garden chat application like Discord or Telegram please.

Right now I'm missing out on Stevenarella chat completely because of the missing IRC bridge, and I'm not going to launch a IRC client specifically for it either. Moving networks to Freenode or some other bridged network would be lovely :smile:

**Comment by PureTryOut** [comment]
I was just thinking about this project again. @iceiix would you consider moving to Freenode or some other bridged-to-Matrix IRC network?

**Comment by PureTryOut** [comment]
Is there any progress on this? I'd still like to have Stevenarella move to some other network so I can join it via Matrix. Freenode or OFTC would be nice.

**Comment by iceiix** [comment]
@PureTryOut Alright I registered a new channel: #stevenarella @ irc.freenode.net. There's still the same channel at irc.esper.net (I lost control of it, but will try to at least idle there). We also now have a discussion forum: https://github.com/iceiix/stevenarella/discussions
