### ISSUE TITLE
1.16.1: Forge (FML2): bad packet id 0x1a in Clientbound Login

### ISSUE THREAD

**Issue by PureTryOut** [iceiix/stevenarella#400]
I tried to join a LAN server but the UI kept hanging on connecting while the console reported the following:

```
thread '<unnamed>' panicked at 'bad packet id 0x1a in Clientbound Login', protocol/src/protocol/versions/v1_16_1.rs:1:1
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: std::panicking::begin_panic_fmt
   8: steven_protocol::protocol::versions::v1_16_1::translate_internal_packet_id
   9: steven_protocol::protocol::packet::packet_by_id
  10: steven_protocol::protocol::Conn::read_packet
  11: stevenarella::server::Server::connect
```

I expected it not to be able to connect as the LAN server had some Forge mods running (which the UI told me, nice!), but I'd love it if the UI showed me as such rather than hanging. Preferably with a clear reason instead of a bad packet message too :stuck_out_tongue_winking_eye:

**Comment by skillman623** [comment]
Hello PureTryOut.
Could I get the modpack name (or a mod list) of the world you were trying to join?
There is also a built in method to record network packets that the client receives that I could try and help you with if you are comfortable with using the command line or shell/batch scripts.

**Comment by PureTryOut** [comment]
Sure, it's not a modpack so here is a list.

- Forge 32.0.108 (MC 1.16.1)
- InventorySorter 18.0.0
- OptiFine HD_U_G2
- Xaeros Minimap 20.20.1
- Xaeros WorldMap 1.10.1

I'm perfectly fine with shell scripts :wink:

**Comment by iceiix** [comment]
> I expected it not to be able to connect as the LAN server had some Forge mods running

This is actually meant to work (or at least, sorta, as well as I can make it), the client will pull the list of mods from the server ping packet and advertise itself as having those mods installed in order to allow connecting to servers with arbitrary Forge mods installed.

Most mods use plugin channels for their custom payloads, so connecting without a real implementation of the client mod mostly gracefully degrades, but some do define their own custom packets for some reason. Currently the only custom mod packet supported is [-0x1a, used by CoFHLib](https://github.com/iceiix/stevenarella/blob/master/protocol/src/protocol/versions/v1_7_10.rs#L102), but more can be added.

To fix this we would need to find out what is packet 0x1a and how is it structured. @PureTryOut if you can rerun with `-n` and attach the contents of `last-packet` that would be a good start, also if you can isolate which mod causes this. I'm guessing InventorySorter 18.0.0, or maybe the Xaeros mods. 

Curious, the custom packet is in the Clientbound Login stage. Maybe some kind of initialization for the minimap or worldmap. Also odd how the packet id is 0x1a whereas 1.7.10's CoFHLib's custom packet id was -0x1a, though maybe that's just a coincidence.

**Comment by iceiix** [comment]
Another possibility, is if this was a change to the login process by 1.16.1 Forge itself, causing the packet to be incorrectly parsed.

Now that I think about it, I've only tested Forge on 1.7.10 - 1.12.2. There was some weirdness with Forge in 1.13.2 but it looks like there are releases (and mods) for 1.14.4, 1.15.2, 1.16.2, worth supporting (1.16.1 "dev-only", but 1.16.2 has a Forge release, support it after https://github.com/iceiix/stevenarella/pull/390 1.16.2 support?). And now I see 1.16.3 (753) is out, always a moving target...

**Comment by iceiix** [comment]
Testing connecting to a 1.16.5 + forge-1.16.5-36.0.1.jar + ironchest-1.16.4-11.2.10.jar server, crashes with a slightly different error, interesting:

thread '<unnamed>' panicked at 'bad packet id 0x19 in Clientbound Login', protocol/src/protocol/versions/v1_16_4.rs:1:1

not sure where these packet is coming from, and why it is 0x19 vs 0x1a. last-packet shows an error message:

```
00000000  19 7f 7b 22 74 72 61 6e  73 6c 61 74 65 22 3a 22  |..{"translate":"|
00000010  64 69 73 63 6f 6e 6e 65  63 74 2e 67 65 6e 65 72  |disconnect.gener|
00000020  69 63 52 65 61 73 6f 6e  22 2c 22 77 69 74 68 22  |icReason","with"|
00000030  3a 5b 22 49 6e 74 65 72  6e 61 6c 20 45 78 63 65  |:["Internal Exce|
00000040  70 74 69 6f 6e 3a 20 6a  61 76 61 2e 6c 61 6e 67  |ption: java.lang|
00000050  2e 4e 75 6d 62 65 72 46  6f 72 6d 61 74 45 78 63  |.NumberFormatExc|
00000060  65 70 74 69 6f 6e 3a 20  46 6f 72 20 69 6e 70 75  |eption: For inpu|
00000070  74 20 73 74 72 69 6e 67  3a 20 5c 22 5c 22 22 5d  |t string: \"\""]|
00000080  7d                                                |}|
00000081
```

so this is a Disconnect packet, in v1_16_4 `0x19 => Disconnect` in clientbound Play. v1_16_1 is `0x1a => Disconnect` also in clientbound Play. The state isn't transitioned from Login to Play. This may be another bug, but real issue is how we are causing the server to hit {"translate":"disconnect.genericReason","with":["Internal Exception: java.lang.NumberFormatException: For input string: \"\""].

I'm guessing this is related to the \0FML\0 tag, which we send `if !forge_mods.is_empty()`. According to https://wiki.vg/Minecraft_Forge_Handshake#FML2_protocol_.281.13_-_Current.29 this should now be \0FML2\0, matching `"fmlNetworkVersion": 2`.
