### ISSUE TITLE
UI: Cmd-V pastes v character (Unable to login with email and password)

### ISSUE THREAD

**Issue by mpfaff** [iceiix/stevenarella#432]
Logging in with an email and password fails with the error "protocol error: ForbiddenOperationException: Invalid credentials. Invalid username or password."

**Comment by mpfaff** [comment]
After adding a log statement to print my password that I was pasting in, I realized that the character "v" was being appended to it when I press Cmd+V. I don't have a Windows or Linux computer available to test whether Ctrl+V has the same issue.

**Comment by iceiix** [comment]
An annoying bug, I've noticed this too (workaround is to delete the spurious "v" after pasting). We'll probably need to cancel the character event after handling the paste command...

**Comment by iceiix** [comment]
Workaround 2: paste with Ctrl-V (it works on macOS too, at least in this app). Still need to figure out how to cancel the character typing with Cmd..

**Comment by iceiix** [comment]
Looking at how other Rust projects handle this, consider https://github.com/alacritty/alacritty (a terminal emulator)

[ReceivedCharacter](https://github.com/alacritty/alacritty/blob/08e111dfae15d2428d87c3a80c68d858b144d287/alacritty/src/event.rs#L1167) calls [received_char](https://github.com/alacritty/alacritty/blob/1260c4bf6ff76bcd078080fe41bf642879543d27/alacritty/src/input.rs#L865) which checks if suppress_chars is set, if so it returns without typing. This flag is set in [key_input](https://github.com/alacritty/alacritty/blob/1260c4bf6ff76bcd078080fe41bf642879543d27/alacritty/src/input.rs#L830) if a keyboard shortcut is handled.

Pressing Cmd-V in Alacritty therefore does not type 'v', even though it does call received_char 'v', because it is suppressed because it is handled as a keyboard shortcut. Cmd-A, however, _does_ type 'a', which might be considered a bug (it is not what I expect, at least).

We could do something similar, already have game.is_ctrl_pressed and game.is_logo_pressed (logo = the "windows" key on PC and "command" key on Mac https://docs.rs/winit/0.24.0/winit/event/struct.ModifiersState.html) set from ModifiersChanged, use flags to suppress typing in ReceivedCharacter
