### ISSUE TITLE
UI: Backspace key isn't working.

### ISSUE THREAD

**Issue by skillman623** [iceiix/stevenarella#481]
The backspace key doesn't appear to do anything. 
The delete key now acts as a backspace key.

**Comment by iceiix** [comment]
hmm, likely caused by: https://github.com/iceiix/stevenarella/commit/0c65cc1e0d632653f7c8baf16ae7831f2ab42e57
https://github.com/iceiix/stevenarella/issues/476

On my system (macOS 11.1), backspace enters 0x7f, which is handled correctly. 

But if other systems enter 0x08, it may not be (src/ui/mod.rs `if c < ' ' {`)).

@skillman623 Can you try testing on this branch: https://github.com/iceiix/stevenarella/pull/482. Also what OS are you on? If that branch doesn't fix it, will have to try to setup a similar environment to reproduce on my end.

**Comment by skillman623** [comment]
I am on windows 10 home with a EN-US keyboard.
I'll test on #482 and report back.

**Comment by skillman623** [comment]
I just tested on #482 and it resolved the backspace issue. However the delete key still acts as a backspace key.
It appears that on Windows the 0x7f is mapped to the [delete key](https://en.wikipedia.org/wiki/Delete_character#Current_use ).

**Comment by iceiix** [comment]
Thanks for testing, I'll merge #482. 

For the delete key, not sure if a reasonable fix there... ideally it should delete forward instead of backwards, but we don't have arrow key navigation within text fields to move the cursor to where this would be possible. And with the platform differences, would have to change behavior based on (operating system?), it gets complicated quickly. The pitfalls of non-native UI widgets...
